defmodule SCXMLTest.ScxmlEventProcessor.Test351 do
  use Statifier.Case

  @moduletag :scxml_w3
  @tag required_features: [
         :assign_elements,
         :basic_states,
         :compound_states,
         :conditional_transitions,
         :data_elements,
         :datamodel,
         :event_transitions,
         :eventless_transitions,
         :final_states,
         :log_elements,
         :onentry_actions,
         :send_delay_expressions,
         :send_elements,
         :wildcard_events
       ]
  @tag conformance: "mandatory", spec: "SCXMLEventProcessor"
  test "test351" do
    xml = """
    <?xml version="1.0" encoding="UTF-8"?>
    <scxml xmlns="http://www.w3.org/2005/07/scxml" initial="s0" datamodel="predicator" version="1.0">
        <datamodel>
            <data id="Var1" />
            <data id="Var2" />
        </datamodel>
        <state id="s0">
            <onentry>
                <send delay="5s" event="timeout" />
                <send type="http://www.w3.org/TR/scxml/#SCXMLEventProcessor" id="send1" event="s0Event" />
            </onentry>
            <transition event="s0Event" target="s1">
                <assign location="Var1" expr="_event.sendid" />
            </transition>
            <transition event="*" target="fail" />
        </state>
        <state id="s1">
            <transition cond="Var1=='send1'" target="s2" />
            <transition target="fail" />
        </state>
        <state id="s2">
            <onentry>
                <send delay="5s" event="timeout" />
                <send event="s0Event2" />
            </onentry>
            <transition event="s0Event2" target="s3">
                <assign location="Var2" expr="_event.sendid" />
            </transition>
            <transition event="*" target="fail" />
        </state>
        <state id="s3">
            <transition cond="Var2 === _statifier_unbound" target="pass" />
            <transition target="fail" />
        </state>
        <final id="pass">
            <onentry>
                <log label="Outcome" expr="'pass'" />
            </onentry>
        </final>
        <final id="fail">
            <onentry>
                <log label="Outcome" expr="'fail'" />
            </onentry>
        </final>
    </scxml>
    """

    description =
      "sendid'. the sending SCXML Processor MUST populate this attribute with the identifier specified in the 'id' attribute or automatically generated by the platform when the send tag is executed in the sending session. (See 6.2 send.) The receiving SCXML Processor MUST use this value as the value of the 'sendid' field in the event that it generates. If the author of the sending session did not specify either the 'id' or 'idlocation' attribute, the sending SCXML Processor MUST leave this attribute empty."

    test_scxml(xml, description, ["pass"], [])
  end
end
